// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpcyxgznzibpbxecmybq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwY3l4Z3puemlicGJ4ZWNteWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2ODYxMjMsImV4cCI6MjA1NTI2MjEyM30.r6Nuv4ofhtLFAGhe43Dyp-zU48QN9HBCXrdT0UXT8V4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);